services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  backend:
    build: 
      context: ./backend
      args:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/movago
      JWT_SECRET: supersecret123
      GMAIL_USER: ilghvm@gmail.com
      GMAIL_APP_PASSWORD: rjqk ayvo kxqx ghwz
      PORT: 3000

  frontend:
    build: 
      context: ./frontend
      args:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "4200:4200"
    depends_on:
      - backend

  tests:
    image: mcr.microsoft.com/playwright:v1.52.0-noble
    working_dir: /app
    volumes:
      - ../:/app
    depends_on:
      - frontend
    command: ["npx", "playwright", "test"]
