name: Playwright E2E Tests (Docker Compose)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js (for wait-on etc.)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env

      - name: Build and start containers
        run: |
          docker-compose -f deploy/docker-compose.yml up --build -d

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:4200

      - name: Run Playwright tests inside container
        run: docker-compose -f deploy/docker-compose.yml run --rm tests

      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
