name: Playwright E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js (for wait-on)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create .env file
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> .env

      - name: Build and start containers
        run: |
          docker compose -f deploy/docker-compose.yml up --build --abort-on-container-exit

      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
